// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://newynczcfjtmzqzjlzfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ld3luY3pjZmp0bXpxempsemZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2OTY5NDEsImV4cCI6MjA2NTI3Mjk0MX0.y9-Y-aMJ3Wk9BatjTS3SqtlhiNfFwPV2q5qv46cIxRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);